### ISSUE TITLE
Can't reset password 

### ISSUE THREAD

**Issue by Sloth-on-meth** [hassio-addons/addon-tasmoadmin#197]
Reinstall didn't reset password. Unable to login.

_Originally posted by @frenck in https://github.com/hassio-addons/addon-tasmoadmin/issues/105#issuecomment-743923214_

**Comment by bsimmo** [comment]
I just needed to reset my passwords, it's good to change them and to be honest I had forgotten it and so had my browsers.
I just uninstall, reboot, reinstalled. (turn SSL off to as it doesn't load and errors in the logs otherwise)

It allowed be to just make a new log in, now with simplified (and pointless now) password.

**Comment by frenck** [comment]
The login shown the first time, is actually for account creation.

Deleting the add-on removes authentication. My comment in there is correct and still hold true.
