### ISSUE TITLE
tasmoadmin cannot update devices (but incorrectly reports success)

### ISSUE THREAD

**Issue by simonlock** [hassio-addons/addon-tasmoadmin#90]
# Problem/Motivation

> tasmoadmin cannot update devices (but incorrectly reports successful updates)

Implement the update as reported by tasmoadmin.

## Actual behavior

> the addon reports successful updates have occurred but in reality, it does not update the tasmota devices.

## Steps to reproduce

>Select and action Devices/Update.

I think one problem (at least in my case) is that the url specified for the update bin-file https://<my.homeassistant.com>:9541/data/firmwares/tasmota.bin is not accessible.

My HA install details:
hassio | true
host_os | HassOS 4.10
installation_type | Home Assistant
os_name | Linux
os_version | 5.4.44
python_version | 3.7.7
supervisor | 227
timezone | Europe/London
version | 0.111.3

**Comment by sinclairpaul** [comment]
https://github.com/hassio-addons/addon-tasmoadmin/blob/master/tasmoadmin/DOCS.md#option-ssl

```Note Tasmota does not support OTA via SSL```

#89 #85 Possibly a few others, unfortunately due to the nature of ESP devices, they don't tend to hold certificate chains.

**Comment by simonlock** [comment]
Very quick to close this issue :-)
Surely retrieving the bin file from HA should work OTA? if HA downloads the bin file to https://<my.homeassistant.com>:9541/data/firmwares/tasmota.bin  it's a local upload to tasmota. Should the file exist and be accessible in this location and be accessible from there?

**Comment by sinclairpaul** [comment]
The device will not be able to resolve the certificate chain, as it does not have the necessary trusted certificates installed (mostly at a guess due to limited memory and storage).

Please see more information in #85 

It was closed quickly as there really isn't much that can be done, you could possibly upload a custom version with the correct chain in it, but that would be out of scope of the addon.
